---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: tomcat-servers
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - selinux :
    - tomcat

- hosts: jenkins-servers
  remote_user: root
  become: no

  roles:
    - deploy
    - build
